### ISSUE TITLE
packaged test harnest throws IOException on linux (ubuntu)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hongweijia/javahidapi#6]
```
What steps will reproduce the problem?
1. download the distribution from the download section (or checkout trunk)
2. run: make -C linux
3. patch the build.xml (ant run assumes the "mac" subfolder in line 78) by 
replacing mac with linux.
4. run: ant
5. run: ant run (also: "sudo ant run" doesn't work)

What is the expected output? What do you see instead?
I would have expected a list (empty or at least one device), but instead, I see 
the following output:
someuser@ubuntu:~/Downloads/javahidapi$ sudo ant run
Buildfile: /home/someuser/Downloads/javahidapi/build.xml

init:

build-project:
     [echo] hidapi: /home/someuser/Downloads/javahidapi/build.xml

run:
     [java] /home/someuser/Downloads/javahidapi/linux
     [java] 
     [java] java.io.IOException: 
     [java]     at com.codeminders.hidapi.HIDManager.listDevices(Native Method)
     [java]     at com.codeminders.hidapi.HIDAPITest.listDevices(HIDAPITest.java:122)
     [java]     at com.codeminders.hidapi.HIDAPITest.main(HIDAPITest.java:34)
     [java] waiting connect/disconnect...


What version of the product are you using? On what operating system?
trunk and the available download. Ubuntu (latest)


```

Original issue reported on code.google.com by `mirkoj...@gmail.com` on 8 Feb 2012 at 10:27

**Comment by GoogleCodeExporter** [comment]
```
I also tested with the latest (trunk version) of the hidapi and there 
everything seems to work as expected. I was able to see my usb devices 
(executed as root only though).
```

Original comment by `mirkoj...@gmail.com` on 8 Feb 2012 at 10:29

**Comment by GoogleCodeExporter** [comment]
```
I checked revision 1488859b113b and there everything works just fine (in case 
that helps)
```

Original comment by `mirkoj...@gmail.com` on 8 Feb 2012 at 11:06

**Comment by GoogleCodeExporter** [comment]
```
thanks. We are finishing some tests and will publish a tarball with new build, 
based on SVN trunk shortly.

Is my understanding that it works OK in trunk but not in release tarball 
correct?

```

Original comment by `kroko...@gmail.com` on 9 Feb 2012 at 1:03
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
hmm, I could have sworn that it didn't work on trunk, but I just checked out 
the trunk again and retested it without any issue. Also detaching and 
reattaching devices worked like a charm with the test program. So I guess this 
one is fixed. Many Thanks!
```

Original comment by `mirkoj...@gmail.com` on 9 Feb 2012 at 1:23

**Comment by GoogleCodeExporter** [comment]
Original comment by `kroko...@gmail.com` on 9 Feb 2012 at 5:11
- Changed state: **Fixed**
